name: appcenter
description: Visual Studio App Center plugin for Flutter applications.
version: 0.2.1
authors: 
  - Alo√Øs Deniel<alois.deniel@outlook.com>
  - Damien Aicheh<damien.aicheh@gmail.com>
homepage: https://github.com/aloisdeniel/flutter_plugin_appcenter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0" 
  
dependencies:
  flutter:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.aloisdeniel.flutter.appcenter
    pluginClass: AppcenterPlugin