name: appcenter
description: Visual Studio App Center plugin for Flutter applications.
version: 0.0.1
author: Alo√Øs Deniel<alois.deniel@outlook.com>
homepage: https://github.com/aloisdeniel/flutter_plugin_appcenter
dependencies:
  flutter:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.aloisdeniel.flutter.appcenter
    pluginClass: AppcenterPlugin